// Up to 1000 users can be imported at once.
const userImportRecords = [
    {
      uid: 'uid1',
      email: 'user1@example.com',
      name: "Drs. MOCH. HATTA",
      passwordHash: Buffer.from('passwordHash1'),
      passwordSalt: Buffer.from('salt1'),
    },
    {
      uid: 'uid2',
      email: 'user2@example.com',
      name: "STUROM ARIF, ST, MT",
      passwordHash: Buffer.from('passwordHash2'),
      passwordSalt: Buffer.from('salt2'),
    },
    {
      uid: 'uid2',
      email: 'user2@example.com',
      name : 'SEHMAN, S. Kom, M. Kom',
      passwordHash: Buffer.from('passwordHash2'),
      passwordSalt: Buffer.from('salt2'),
    },
    {
      uid: 'uid2',
      email: 'user2@example.com',
      name: 'SEHMAN, S. Kom, M. Kom',
      passwordHash: Buffer.from('passwordHash2'),
      passwordSalt: Buffer.from('salt2'),
    },
    {
      uid: 'uid2',
      email: 'user2@example.com',
      name: 'KHAIRIL ANAM, S. Kom, M. Kom',
      passwordHash: Buffer.from('passwordHash2'),
      passwordSalt: Buffer.from('salt2'),
    },
    {
      uid: 'uid2',
      email: 'user2@example.com',
      name: 'BAYU CHARISMA, S.Si, M.Si',
      passwordHash: Buffer.from('passwordHash2'),
      passwordSalt: Buffer.from('salt2'),
    },
    {
      uid: 'uid2',
      email: 'user2@example.com',
      name: 'NAMBI SEMBILU, S.Kom, M.Kom',
      passwordHash: Buffer.from('passwordHash2'),
      passwordSalt: Buffer.from('salt2'),
    },
    {
      uid: 'uid2',
      email: 'user2@example.com',
      name: 'AGUNG SANTOSO, S. Kom, M. Kom',
      passwordHash: Buffer.from('passwordHash2'),
      passwordSalt: Buffer.from('salt2'),
    },
    {
      uid: 'uid2',
      email: 'user2@example.com',
      name: 'M. FARKHAN, S. Kom',
      passwordHash: Buffer.from('passwordHash2'),
      passwordSalt: Buffer.from('salt2'),
    },
    {
      uid: 'uid2',
      email: 'user2@example.com',
      name: 'ULIYONTANG, ST',
      passwordHash: Buffer.from('passwordHash2'),
      passwordSalt: Buffer.from('salt2'),
    },{
      uid: 'uid2',
      email: 'user2@example.com',
      name: 'YESSI NOVIA, S. Kom, M. Kom',
      passwordHash: Buffer.from('passwordHash2'),
      passwordSalt: Buffer.from('salt2'),
    },{
      uid: 'uid2',
      email: 'user2@example.com',
      name: 'AHMAD BAHRUL, S.Pd, M.Pd',
      passwordHash: Buffer.from('passwordHash2'),
      passwordSalt: Buffer.from('salt2'),
    },{
      uid: 'uid2',
      email: 'user2@example.com',
      name: 'YUNITA NUR AFIFAH, S.Pd, M.Si',
      passwordHash: Buffer.from('passwordHash2'),
      passwordSalt: Buffer.from('salt2'),
    },{
      uid: 'uid2',
      email: 'user2@example.com',
      name: 'ONNY DWI HARTONO, S.Kom',
      passwordHash: Buffer.from('passwordHash2'),
      passwordSalt: Buffer.from('salt2'),
    },{
      uid: 'uid2',
      email: 'user2@example.com',
      name: 'TEGUH PRADANA, S.Kom, M.Kom',
      passwordHash: Buffer.from('passwordHash2'),
      passwordSalt: Buffer.from('salt2'),
    },{
      uid: 'uid2',
      email: 'user2@example.com',
      name: 'DHANIYAR, S.Pd, M.Pd',
      passwordHash: Buffer.from('passwordHash2'),
      passwordSalt: Buffer.from('salt2'),
    }
  ];